import { Router } from "express";
import ClassesController from "../controllers/ClassesController";
import CommentsController from "../controllers/CommentsController";
import AuthController from "../controllers/AuthController";
import MiddlewareJwt from "../middlewares/jwt";
const routes = Router();
routes.use(MiddlewareJwt.checkAuth);
routes.get("/classes", ClassesController.list);
routes.get("/classes/:id", ClassesController.selectOne);
routes.delete("/classes/:id", ClassesController.deleteOne);
routes.post("/classes", ClassesController.create);
routes.put("/classes", ClassesController.update);
routes.post("/classes/comments", CommentsController.create);
routes.delete("classes/comments/:id", CommentsController.delete);
routes.delete("classes/comments/deleteone", CommentsController.deleteOne);
routes.get("/classes/comments", CommentsController.list);
routes.post("/login", AuthController.auth);
routes.get("/login", MiddlewareJwt.checkAuth);
export default routes;
